FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Gera o Prisma Client dentro do container
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]